<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Fri, 18 Nov 2016 11:50:13 +0100
 */

$conf['title'] = 'Dokuwiki';
$conf['lang'] = 'fr';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['updatecheck'] = 0;
$conf['plugin']['gallery']['thumbnail_width'] = 1100;
$conf['plugin']['gallery']['thumbnail_height'] = 900;
$conf['plugin']['gallery']['image_width'] = 1100;
$conf['plugin']['gallery']['image_height'] = 900;
$conf['plugin']['gallery']['options'] = 'cache,lightbox';

// end auto-generated content
